name: Release

on:
  push:
    tags:
      - 'v*' # Например v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Pack tarball
        run: npm pack

      - name: Upload tarball as artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-package
          path: ./*.tgz

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}